Pharmacyproject/Client/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static



app_name = "ecomapp"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
     path('edit-profile/', edit_profile, name='editprofile'),  
      path('order/<int:order_id>/bill/pdf/', order_pdf, name='order_pdf'),

]

Pharmacyproject/Pharmacyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Client.urls")),
    path("pharmacist/",include("pharmacist.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pharmacyproject/Client/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    # email = models.EmailField()
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    manufacture_date = models.DateField(blank=True)
    expiry_date = models.DateField(blank=True)
    hex = models.IntegerField(null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(
        max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

Pharmacyproject/templates/Pharmacyregistration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    
        <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <!-- bootstrap js cdn link -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        
        <style>
            .margin-custom{
                float: left !important;
            }
            .custom-margin{
                margin-top: 20px;
            }
            h1 {
                margin: 0;
                padding: 0;
              }
    
              .footer {
                background-color: whitesmoke;
                color: black;
                padding: 20px;
              }
              
              .footer-content {
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
              }
              
              .footer-column {
                flex-basis: 33.33%;
              }
              
              .footer h3 {
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              
              .footer ul {
                list-style: none;
                padding: 0;
              }
              
              .footer ul li {
                margin-bottom: 5px;
              }
              
              .footer-bottom {
                text-align: center;
                margin-top: 20px;
                font-size: 12px;
              }
              
        </style>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">Sajilo Pharmacy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                    
           
            </ul>
            
            </div>
            <!-- <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            
            </form> -->
        </div>
        </nav>
    </body>
   

    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <h3>Pharmacist Registration Form</h3><hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-primary">Register as a Pharmacist</button>
                </form>
                <p> Already have an account? <a href="{% url 'Pharmacist:pharmacist.login' %}">Login here</a></p>
            </div>
        </div>
    </div>
</body>
</html>

Pharmacyproject/templates/addtocart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

Pharmacyproject/templates/allproducts.html
{% extends 'base.html' %}

{% block title %} All Products {% endblock %}

{% block content %}
<div class="container">
    <hr>
    
    {% for cat in allcategories %}
    <h4>{{ cat.title }}</h4><hr>
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 g-4">
        {% for p in cat.product_set.all %}
        <div class="col mb-3">
            <div class="card p-3 shadow-lg">
                <h6 style="height:30px;"><a href="{% url 'ecomapp:productdetail' p.slug %}">{{ p.title }}</a></h6>
                <img src="{{ p.image.url }}" alt="" class="img-fluid" style="height: 200px; object-fit: cover;">
                <p class="mt-3">Price: <strike>Rs. {{ p.marked_price }}</strike> Rs. {{ p.selling_price }}</p>
                {% if p.hex != 0 %}
                    <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
                {% else %}
                    <button class="btn btn-primary" disabled>Out of Stock</button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    
</div>
{% endblock %}

Pharmacyproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- bootstrap js cdn link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-...">
     
    <style>
        .margin-custom{
            float: left !important;
        }
        .custom-margin{
            margin-top: 20px;
        }
        h1 {
            margin: 0;
            padding: 0;
          }

          .footer {
            background-color: whitesmoke;
            color: black;
            padding: 20px;
          }
          
          .footer-content {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
          }
          
          .footer-column {
            flex-basis: 33.33%;
          }
          
          .footer h3 {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 10px;
          }
          
          .footer ul {
            list-style: none;
            padding: 0;
          }
          
          .footer ul li {
            margin-bottom: 5px;
          }
          
          .footer-bottom {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
          }
          
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-...">

</head>


<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="{% url 'ecomapp:home' %}">
      <img src="https://static.vecteezy.com/system/resources/previews/017/347/825/original/creative-medical-pharmacy-logo-design-design-concept-free-vector.jpg" alt="Sajilo Pharmacy Logo" height="40">
  </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ml-3">
                <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Categories</a>
            </li>
            <li class="nav-item ml-3">
              <a class="nav-link" href="{% url 'ecomapp:mycart' %}">
                  <i class="fas fa-shopping-cart"></i> Cart
              </a>
          </li>
          
        </ul>
        <div class="margin-custom">
            <div class="nav-item dropdown margin-custom">
                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if request.user.is_authenticated %}
                        {{ request.user.customer.full_name }}
                    {% else %}
                        Account
                    {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.customer %}
                        <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                        <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
                        <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

            

   
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <div class="footer-content">
          <div class="footer-column">
            <h3>Ways to Shop</h3>
            <ul>
              <li>Home</li>
              <li>About us</li>
              <li>Contact Us</li>
              <li>Categories</li>
              <li>Search</li>
            </ul>
          </div><div class="footer-column">
            <h3>My account</h3>
            <ul>
              <li>My account</li>
              <li>Orders</li>
              <li>Addresses</li>
              <li>Cart</li>
              
            </ul>
          </div><div class="footer-column">
            <h3>About us</h3>
            <ul>
              <li>About us</li>
              <li>Company name: Sajilo Epharmacy</li>
              <li>Address: Jhamsikhel, Lalitpur, Nepal</li>
              <li>Email: care@sajilopharmacy.com.np</li>
              
                                  <ul class="list-unstyled">
                        <li>Phone: 9808787939</li>
                        <li>
                            <a href="https://www.facebook.com/your-page-url" target="_blank">
                                <i class="fab fa-facebook"></i>
                            </a>
                            <a href="https://www.instagram.com/your-profile-url" target="_blank" class="instagram-icon">
                              <i class="fab fa-instagram"></i>
                            </a>
                            <a href="https://www.linkedin.com/in/your-profile-url" target="_blank">
                                <i class="fab fa-linkedin"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <style>
              .instagram-icon {
                  color: #E1306C; /* Replace with your desired color */
              }
          </style>
            
            </ul>
          </div>
        </div>
        <div class="footer-bottom"><br><br>
          <p>
            &copy; 2023 Sajilo ePharmacy Pvt. Ltd. All rights reserved.
           </p>
        </div>
      </footer>
      

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>

</html>

Pharmacyproject/templates/customerorderdetail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Order Detail {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>Order Detail</h3>
            <a href="{% url 'ecomapp:order_pdf' ord_obj.id %}" class="btn btn-primary">
                <i class="fas fa-download"></i> Download Bill (PDF)
            </a>
            
            <hr>


            <p><span class="font-weight-bold">Order ID: </span> #ORDER_{{ord_obj.id}}</p>
            <p><span class="font-weight-bold">Order Status: </span> {{ord_obj.order_status}}</p>
            <p><span class="font-weight-bold">Order On: </span> {{ord_obj.created_at}}({{ord_obj.created_at|timesince}} ago)</p>
            <p><span class="font-weight-bold">Customer Information: </span> By {{ord_obj.ordered_by}}, {{ord_obj.mobile}}</p>
            <p><span class="font-weight-bold">Shipping Address: </span> By {{ord_obj.shipping_address}} ({{ord_obj.email}})</p>
            
            <h4>Ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a target="_blank" href="{% url 'ecomapp:productdetail' cp.product.slug %}">{{cp.product.title}}({{cp.product.id}})</a></td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total: </th>
                        <th>Rs {{ord_obj.total|intcomma}}/-</th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

Pharmacyproject/templates/editprofile.html
<body>
    <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- bootstrap js cdn link -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    
    <style>
        .margin-custom{
            float: left !important;
        }
        .custom-margin{
            margin-top: 20px;
        }
        h1 {
            margin: 0;
            padding: 0;
          }

          .footer {
            background-color: whitesmoke;
            color: black;
            padding: 20px;
          }
          
          .footer-content {
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
          }
          
          .footer-column {
            flex-basis: 33.33%;
          }
          
          .footer h3 {
            font-size: 16px;
            font-weight: bold;
            margin-bottom: 10px;
          }
          
          .footer ul {
            list-style: none;
            padding: 0;
          }
          
          .footer ul li {
            margin-bottom: 5px;
          }
          
          .footer-bottom {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
          }
          
    </style>

<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="{% url 'ecomapp:home' %}">
        <img src="https://static.vecteezy.com/system/resources/previews/017/347/825/original/creative-medical-pharmacy-logo-design-design-concept-free-vector.jpg" alt="Sajilo Pharmacy Logo" height="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Categories</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Cart</a>
        </li>
        
        <!-- <li class="nav-item dropdown margin-custom">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if request.user.customer %}
            <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
            <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
            <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
            {% endif %}
            </div>
        </li> -->
        </ul>
        <div class="margin-custom">
            <div class="nav-item dropdown margin-custom">
              <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if request.user.is_authenticated %}
                    {{ request.user.customer.full_name }}
                {% else %}
                    Account
                {% endif %}
            </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </div>
        </div>
        <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
        <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
        <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
        
        </form>
    </div>
    </nav>
</body>
    
<h3>Edit Profile</h3><hr>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>