Pharmacyproject/Client/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static



app_name = "ecomapp"
urlpatterns = [
    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
     path('edit-profile/', edit_profile, name='editprofile'),  
      path('order/<int:order_id>/bill/pdf/', order_pdf, name='order_pdf'),

]

Pharmacyproject/Pharmacyproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Client.urls")),
    path("pharmacist/",include("pharmacist.urls"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pharmacyproject/pharmacist/urls.py
from . import views
from .views import *
from django.urls import path
from django.contrib.auth.views import LogoutView

app_name = "Pharmacist"
urlpatterns = [
path("registrer",PharmacistRegistrationView.as_view(), name="pharmacist.registration"),
path("", PharmacistLoginView.as_view(), name="pharmacist.login"),
path('add/',views.product_create, name= 'product.create'),
path('list',views.product_list, name= 'product.list'),
path('store',views.product_store, name= 'product.store'),
path('delete/<int:id>',views.product_delete, name= 'product.delete'),
# path('update/<int:id>/', views.product_update, name='product.update')
path("update/<int:id>/", views.product_edit, name="product.update"),
path('orders/', views.admin_orders, name='admin_orders'),
path("logout/", LogoutView.as_view(next_page="Pharmacist:pharmacist.login"), name="pharmacist.logout"),
path('stock/', OutOfStockView.as_view(), name='out_of_stock'),
]

Pharmacyproject/pharmacist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pharamcist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pharmacy_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    phone_no= models.CharField(max_length=200, null=True, blank=True)
    license_number = models.CharField(max_length=200, null=True, blank=True)
    company_pic= models.ImageField(upload_to="products")
    joined_on = models.DateTimeField(auto_now_add=True)
    
   

    def str(self):
        return self.full_name

Pharmacyproject/pharmacist/forms.py
from django import forms
from .models import Pharamcist
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password


class PharmacistLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


class PharmacistRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
        validators=[validate_password]
    )
    cpassword = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput
    )
    class Meta:
        model = Pharamcist
        fields = ["username", "password", "cpassword", "email", "pharmacy_name", "address","phone_no","license_number","company_pic"]
    
    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")
        return uname
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        cpassword = cleaned_data.get("cpassword")

        if password and cpassword and password != cpassword:
            self.add_error('cpassword', "Passwords And Confirm Password do not match.")

        return cleaned_data
     

Pharmacyproject/pharmacist/views.py
from django.shortcuts import render
from django.shortcuts import redirect, render
from Client.models import Product, Category
from pharmacist import service
from django.views.generic import CreateView,FormView
from pharmacist.forms import PharmacistRegistrationForm,PharmacistLoginForm
from .models import *
from pharmacist.service import create_product
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth import login,authenticate
from django.urls import reverse


class PharmacistLoginView(FormView):
    template_name = "Pharmacistlogin.html"
    form_class = PharmacistLoginForm
    success_url = reverse_lazy("Pharmacist:product.list")

    # form_valid method is a type of post method and is available in createview formview and updateview
    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Pharamcist.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})

        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return self.success_url


class PharmacistRegistrationView(CreateView):
    template_name = "Pharmacyregistration.html"
    form_class = PharmacistRegistrationForm
    success_url = reverse_lazy("Pharmacist:product.list")

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        user = User.objects.create_user(username, email, password)
        form.instance.user = user
        login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        if "next" in self.request.GET:
            next_url = self.request.GET.get("next")
            return next_url
        else:
            return reverse("Pharmacist:pharmacist.login")
        
def product_list(request):
    product = Product.objects.all()
    data = {
        'product':product,
    }
    return render(request,'pharmacist/list.html',data)
   

# def product_create(request):
#     data={
        
#         'category':service.productCategory(request)
#     }
#     return render(request,'pharmacist/add.html',data)

def product_create(request):
    if request.method == 'POST':
        create_product(request)
        return redirect('Pharmacist:product.list')
    else:
        category = Category.objects.all()
        context = {'category': category}
        return render(request, 'pharmacist/add.html', context)

#view for the list view 
def product_store(request):
    service.storeProduct(request)
    return redirect('Pharmacist:product.list')

# #view for the edit the registration from
# def product_edit(request,id):
#     vendor=service.getproductId(id)
#     data = {
#         'title'  : 'vendor',
#         'vendor':vendor,
#         'category':service.productCategory(request)  
#     }
#     return render(request,'vendor/form.html',data) category

def product_edit(request, id):
    if request.method == 'POST':
        service.updateproduct(request, id)
        return redirect('Pharmacist:product.list')
    else:
        product = service.getproductId(id)
        category = Category.objects.all()
        context = {'product': product, 'category': category}
        return render(request, 'pharmacist/form.html', context)


def product_update(request, id):
    if request.method == 'POST':
        service.updateproduct(request, id)
        return redirect('Pharmacist:product.list')
    else:
        product = Product.objects.get(id=id)(id)
        categories = service.getallcategories()
        return render(request, 'form.html', {'product': product, 'category': categories})


#view for the delete registration from
def product_delete(request,id):
    service.deleteproduct(id)
    return redirect('Pharmacist:product.list')

from Client.models import Order

def admin_orders(request):
    orders = Order.objects.all()
    return render(request, 'pharmacist/orders.html', {'orders': orders})

def pharmacist_logout(request):
    logout(request)
    return redirect('Pharmacist:pharmacist.login')

from django.shortcuts import render
from django.views.generic import TemplateView
from Client.models import Product

class OutOfStockView(TemplateView):
    template_name = 'pharmacist/out_of_stock.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Retrieve out-of-stock products
        out_of_stock_products = Product.objects.filter(hex=0)
        context['out_of_stock_products'] = out_of_stock_products
        return context

Pharmacyproject/pharmacist/templates/pharmacist/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

    
        <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <!-- bootstrap js cdn link -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        
        <style>
            .margin-custom{
                float: left !important;
            }
            .custom-margin{
                margin-top: 20px;
            }
            h1 {
                margin: 0;
                padding: 0;
              }
    
              .footer {
                background-color: whitesmoke;
                color: black;
                padding: 20px;
              }
              
              .footer-content {
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
              }
              
              .footer-column {
                flex-basis: 33.33%;
              }
              
              .footer h3 {
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              
              .footer ul {
                list-style: none;
                padding: 0;
              }
              
              .footer ul li {
                margin-bottom: 5px;
              }
              
              .footer-bottom {
                text-align: center;
                margin-top: 20px;
                font-size: 12px;
              }
              
        </style>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'Pharmacist:product.list' %}">Sajilo Pharmacy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.create'  %}">Add products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">View products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pharmacist:admin_orders' %}">All orders </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pharmacist:out_of_stock' %}">Stock</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pharmacist:pharmacist.login' %}">Log out </a>
          </li>
          
          
            
            
            </ul>
            
            </div>
            
        </div>
        </nav>
        

<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            

             <form method="POST" action="{% url 'Pharmacist:product.create' %}" enctype="multipart/form-data">
      {% csrf_token %}
        
        <div class="form-group">
          <label for="title">Product Name:</label>
          <input type="text" class="form-control" id="title" name="title" value="{% if product.title %}{{product.title}}{% endif %}" placeholder="Full Name">
        </div>
      
        <div class="form-group">
          <label for="category">Category:</label>
          <select class="form-select" name="category" id="category">
            {% for i in category %}
            <option value="{{i.id}}" {% if category.category_id and category.category_id == i.id %}selected{% endif %}>{{ i.title }}</option>
            {% endfor %}
          </select>
        </div>
      
        <div class="mb-3">
          <label for="slug">Slug:</label>
          <input type="text" name="slug" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="image">Image:</label>
          <input type="file" name="image" class="form-control-file">
        </div>
      
        <div class="mb-3">
          <label for="marked_price">Marked Price:</label>
          <input type="text" name="marked_price" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="selling_price">Selling Price:</label>
          <input type="text" name="selling_price" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="manufacture_date">Manufacture Date:</label>
          <input type="date" name="manufacture_date" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="expiry_date">Expiry Date:</label>
          <input type="date" name="expiry_date" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="hex">HSN:</label>
          <input type="text" name="hex" class="form-control">
        </div>
      
        <div class="mb-3">
          <label for="description">Description:</label>
          <textarea name="description" class="form-control"></textarea>
        </div>
      
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
</div>
</div>
      
</body>

</html>

Pharmacyproject/pharmacist/templates/pharmacist/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

    
        <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <!-- bootstrap js cdn link -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        
        <style>
            .margin-custom{
                float: left !important;
            }
            .custom-margin{
                margin-top: 20px;
            }
            h1 {
                margin: 0;
                padding: 0;
              }
    
              .footer {
                background-color: whitesmoke;
                color: black;
                padding: 20px;
              }
              
              .footer-content {
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
              }
              
              .footer-column {
                flex-basis: 33.33%;
              }
              
              .footer h3 {
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              
              .footer ul {
                list-style: none;
                padding: 0;
              }
              
              .footer ul li {
                margin-bottom: 5px;
              }
              
              .footer-bottom {
                text-align: center;
                margin-top: 20px;
                font-size: 12px;
              }
              
        </style>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">Sajilo Pharmacy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.create'  %}">Add products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">View products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Pharmacist:admin_orders' %}">All orders </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Pharmacist:out_of_stock' %}">Stock</a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Pharmacist:pharmacist.login' %}">Log out </a>
        </li>
        
          
            
            
            </ul>
            
            </div>
            
        </div>
        </nav>
        <body>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">


            <form method="POST" action="{% url 'Pharmacist:product.update' product.id %}" enctype="multipart/form-data">
              {% csrf_token %}
        
        <div class="form-group">
          <label for="title">Product Name:</label>
          <input type="text" class="form-control" id="title" name="title" value="{% if product.title %}{{product.title}}{% endif %}" placeholder="Full Name">
        </div>
      
        <div class="form-group">
          <label for="category">Category:</label>
          <select class="form-select" name="category" id="category">
            {% for i in category %}
            <option value="{{i.id}}" {% if category.category_id and category.category_id == i.id %}selected{% endif %}>{{ i.title }}</option>
            {% endfor %}
          </select>
        </div>
      
        <div class="mb-3">
          <label for="slug">Slug:</label>
          <input type="text" name="slug" class="form-control" value="{{ product.slug }}">
        </div>
      
        <div class="mb-3">
          <label for="image">Image:</label>
          {% if product.image %}
            <img src="{{ product.image.url }}" alt="Product Image" style="max-width: 200px;">
          {% endif %}
          <input type="file" name="image" class="form-control-file">
        </div>
        
      
        <div class="mb-3">
          <label for="marked_price">Marked Price:</label>
          <input type="text" name="marked_price" class="form-control" value="{{ product.marked_price }}" >
        </div>
      
        <div class="mb-3">
          <label for="selling_price">Selling Price:</label>
          <input type="text" name="selling_price" class="form-control" value=" {{product.selling_price }}">
        </div>
      
        <div class="mb-3">
          <label for="manufacture_date">Manufacture Date:</label>
          <input type="date" name="manufacture_date" class="form-control" value="{{ product.manufacture_date|date:'Y-m-d' }}">
      </div>
      
      <div class="mb-3">
          <label for="expiry_date">Expiry Date:</label>
          <input type="date" name="expiry_date" class="form-control" value="{{ product.expiry_date|date:'Y-m-d' }}">
      </div>
      
        <div class="mb-3">
          <label for="hex">HSN:</label>
          <input type="text" name="hex" class="form-control" value="{{ product.hex }}">
        </div>
      
        <div class="mb-3">
          <label for="description">Description:</label>
          <textarea name="description" class="form-control">{{ product.description }}</textarea>
      </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
</div>
</div>
      
</body>

</html>

Pharmacyproject/pharmacist/templates/pharmacist/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

    
        <!DOCTYPE html>
    <html lang="en">
    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <!-- bootstrap js cdn link -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        
        <style>
            .margin-custom{
                float: left !important;
            }
            .custom-margin{
                margin-top: 20px;
            }
            h1 {
                margin: 0;
                padding: 0;
              }
    
              .footer {
                background-color: whitesmoke;
                color: black;
                padding: 20px;
              }
              
              .footer-content {
                display: flex;
                justify-content: space-between;
                flex-wrap: wrap;
              }
              
              .footer-column {
                flex-basis: 33.33%;
              }
              
              .footer h3 {
                font-size: 16px;
                font-weight: bold;
                margin-bottom: 10px;
              }
              
              .footer ul {
                list-style: none;
                padding: 0;
              }
              
              .footer ul li {
                margin-bottom: 5px;
              }
              
              .footer-bottom {
                text-align: center;
                margin-top: 20px;
                font-size: 12px;
              }
              
        </style>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'Pharmacist:product.list' %}">Sajilo Pharmacy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.create'  %}">Add products</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:product.list' %}">View products</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:admin_orders' %}">All orders </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:out_of_stock' %}">Stock</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'Pharmacist:pharmacist.login' %}">Log out </a>
            </li>
            
            
            </ul>
            
            </div>
            
        </div>
        </nav>
        <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  
    <div class="container ">
        <h2 class="text-center">Pharmacy List</h2>
        <table class="table table-pink table-hover table-bordered text-center">
            <thead>
                <tr class="bg-primary text-white ">
                    <th>No.</th>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Selling Price</th>
                    <th>Image</th>
                    <th>Action</th>
                   
                </tr>
            </thead>
    
            <tbody>
                {% if product %}
                {% for e in product %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>{{e.title}}</td>
                    <td>{{e.category.title}}</td>
                    <td>{{e.selling_price}}</td>
                    <td>
                        <img src="{{ e.image.url }}" alt="{{ e.title }}" style="width: 100px; height: auto;">
                    </td>
                    <td>
                        <a href="{% url 'Pharmacist:product.delete' e.id %}">Delete</a>
                        <a href="{% url 'Pharmacist:product.update' e.id %}">Edit</a>
                    </td>
    
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="4"><span>
                            No Record Found !
                        </span>
                    </td>
                </tr>
    
                {% endif %}
            </tbody>
        </table>
        
    </div>
</body>
</html>